PRODUCT_COPY_FILES += \
	vendor/bq/kaito_wifi/propietary/bin/nvram_daemon:system/bin/nvram_daemon \
	vendor/bq/kaito_wifi/propietary/bin/mdnsd:system/bin/mdnsd \
	vendor/bq/kaito_wifi/propietary/bin/bmm050d:system/bin/bmm050d \
	vendor/bq/kaito_wifi/propietary/bin/bmm056d:system/bin/bmm056d \
	vendor/bq/kaito_wifi/propietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
	vendor/bq/kaito_wifi/propietary/bin/thermal_manager:system/bin/thermal_manager \
	vendor/bq/kaito_wifi/propietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
	vendor/bq/kaito_wifi/propietary/bin/mtkbt:system/bin/mtkbt \
	vendor/bq/kaito_wifi/propietary/bin/muxreport:system/bin/muxreport \
	vendor/bq/kaito_wifi/propietary/bin/ccci_fsd:system/bin/ccci_fsd \
	vendor/bq/kaito_wifi/propietary/bin/lsm303md:system/bin/lsm303md \
	vendor/bq/kaito_wifi/propietary/bin/6620_launcher:system/bin/6620_launcher \
	vendor/bq/kaito_wifi/propietary/bin/gsm0710muxd:system/bin/gsm0710muxd \
	vendor/bq/kaito_wifi/propietary/bin/drvbd:system/bin/drvbd \
	vendor/bq/kaito_wifi/propietary/bin/wmt_loader:system/bin/wmt_loader \
	vendor/bq/kaito_wifi/propietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
	vendor/bq/kaito_wifi/propietary/lib/libdpframework.so:system/lib/libdpframework.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
	vendor/bq/kaito_wifi/propietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
	vendor/bq/kaito_wifi/propietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
	vendor/bq/kaito_wifi/propietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
	vendor/bq/kaito_wifi/propietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
	vendor/bq/kaito_wifi/propietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
	vendor/bq/kaito_wifi/propietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
	vendor/bq/kaito_wifi/propietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
	vendor/bq/kaito_wifi/propietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
	vendor/bq/kaito_wifi/propietary/lib/libion.so:system/lib/libion.so \
	vendor/bq/kaito_wifi/propietary/lib/libnvram.so:system/lib/libnvram.so \
	vendor/bq/kaito_wifi/propietary/lib/libbluetoothem_mtk.so:system/lib/libbluetoothem_mtk.so \
	vendor/bq/kaito_wifi/propietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
	vendor/bq/kaito_wifi/propietary/lib/lib3a.so:system/lib/lib3a.so \
	vendor/bq/kaito_wifi/propietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
	vendor/bq/kaito_wifi/propietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
	vendor/bq/kaito_wifi/propietary/lib/hw/gralloc.mt6592.so:system/lib/hw/gralloc.mt6592.so \
	vendor/bq/kaito_wifi/propietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
	vendor/bq/kaito_wifi/propietary/lib/hw/hwcomposer.mt6592.so:system/lib/hw/hwcomposer.mt6592.so \
	vendor/bq/kaito_wifi/propietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
	vendor/bq/kaito_wifi/propietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
	vendor/bq/kaito_wifi/propietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
	vendor/bq/kaito_wifi/propietary/lib/mtk-rilmd2.so:system/lib/mtk-rilmd2.so \
	vendor/bq/kaito_wifi/propietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
	vendor/bq/kaito_wifi/propietary/lib/libblisrc.so:system/lib/libblisrc.so \
	vendor/bq/kaito_wifi/propietary/lib/libmnl.so:system/lib/libmnl.so \
	vendor/bq/kaito_wifi/propietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam.client.so:system/lib/libcam.client.so \
	vendor/bq/kaito_wifi/propietary/lib/libbwc.so:system/lib/libbwc.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
	vendor/bq/kaito_wifi/propietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
	vendor/bq/kaito_wifi/propietary/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
	vendor/bq/kaito_wifi/propietary/lib/libimageio.so:system/lib/libimageio.so \
	vendor/bq/kaito_wifi/propietary/lib/libfile_op.so:system/lib/libfile_op.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
	vendor/bq/kaito_wifi/propietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
	vendor/bq/kaito_wifi/propietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
	vendor/bq/kaito_wifi/propietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
	vendor/bq/kaito_wifi/propietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
	vendor/bq/kaito_wifi/propietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
	vendor/bq/kaito_wifi/propietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
	vendor/bq/kaito_wifi/propietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
	vendor/bq/kaito_wifi/propietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
	vendor/bq/kaito_wifi/propietary/lib/librilmtk.so:system/lib/librilmtk.so \
	vendor/bq/kaito_wifi/propietary/lib/librilmtkmd2.so:system/lib/librilmtkmd2.so \
	vendor/bq/kaito_wifi/propietary/lib/libwebrtc_audio_preprocessing.so:system/lib/libwebrtc_audio_preprocessing.so \
	vendor/bq/kaito_wifi/propietary/lib/libsched.so:system/lib/libsched.so \
	vendor/bq/kaito_wifi/propietary/lib/libbtcust.so:system/lib/libbtcust.so \
	vendor/bq/kaito_wifi/propietary/lib/libbtcusttable.so:system/lib/libbtcusttable.so \
	vendor/bq/kaito_wifi/propietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
	vendor/bq/kaito_wifi/propietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
	vendor/bq/kaito_wifi/propietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
	vendor/bq/kaito_wifi/propietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
	vendor/bq/kaito_wifi/propietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
	vendor/bq/kaito_wifi/propietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
	vendor/bq/kaito_wifi/propietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
	vendor/bq/kaito_wifi/propietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
	vendor/bq/kaito_wifi/propietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
	vendor/bq/kaito_wifi/propietary/lib/libMali.so:system/lib/libMali.so \
	vendor/bq/kaito_wifi/propietary/lib/libssladp.so:system/lib/libssladp.so \
	vendor/bq/kaito_wifi/propietary/lib/libm4u.so:system/lib/libm4u.so \
	vendor/bq/kaito_wifi/propietary/xbin/mnld:system/xbin/mnld \
	vendor/bq/kaito_wifi/propietary/xbin/libmnlp_mt6592:system/xbin/libmnlp_mt6592 \
	vendor/bq/kaito_wifi/propietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6572_82_patch_e1_0_hdr.bin:system/etc/firmware/mt6572_82_patch_e1_0_hdr.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6572_82_patch_e1_1_hdr.bin:system/etc/firmware/mt6572_82_patch_e1_1_hdr.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
	vendor/bq/kaito_wifi/propietary/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
	vendor/bq/kaito_wifi/propietary/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
	vendor/bq/kaito_wifi/propietary/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6 \
	vendor/bq/kaito_wifi/propietary/etc/firmware/WIFI_RAM_CODE_MT6582:system/etc/firmware/WIFI_RAM_CODE_MT6582 \
	vendor/bq/kaito_wifi/propietary/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
	vendor/bq/kaito_wifi/propietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg
